FROM apache/airflow:3.1.0

USER airflow

RUN pip install --no-cache-dir clickhouse-connect

FROM apache/airflow:3.1.0

USER airflow

RUN pip install --no-cache-dir \
    clickhouse-connect \
    dbt-core \
    dbt-clickhouse