services:
  clickhouse:
    image: clickhouse:latest
    container_name: olist-clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DB=olist
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: unless-stopped

volumes:
  clickhouse_data:
